version: "3"
services:
  testsrv_nginx:
    hostname: testsrv_nginx
    restart: always
    container_name: testsrv_nginx
    image: nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  testsrv_node_pm2:
    hostname: testsrv_node_pm2
    restart: always
    container_name: testsrv_node_pm2
    build: .
    context: ./node_pm2
    expose:
      - 5000
  testsrv_redis:
    hostname: testsrv_redis
    restart: always
    container_name: testsrv_redis
    image: redis
    expose:
      - 6443
