version: "3"
services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    expose:
      - 80
      - 443
  node_pm2:
    hostname: node_pm2
    container_name: node_pm2
    build: .
    context: ./node_pm2
    expose:
      - 5000
  redis:
    hostname: redis
    container_name: redis
    image: redis
    expose:
      - 6443
