version: "3"
services:
  webserver:
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
  nodejs:
    hostname: nodejs
    container_name: nodejs
    image: node:12
    expose:
      - 80
  redis:
    hostname: redis
    container_name: redis
    image: redis
    expose:
      - 6443
