version: "3"
services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    expose:
      - 80
      - 443
  nodejs:
    hostname: nodejs
    container_name: nodejs
    image: nodejs
    expose:
      - 80
  redis:
    hostname: redis
    container_name: redis
    image: redis
    expose:
      - 6443
