version: "3"
services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
  node_pm2:
    hostname: node_pm2
    container_name: node_pm2
    build: ./node_pm2
    expose:
      - 5000
  redis:
    hostname: redis
    container_name: redis
    image: redis
    expose:
      - 6443
