version: "3"
services:
  frontend_nginx:
    hostname: frontend_nginx
    container_name: frontend_nginx
    image: nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    expose:
      - 80
      - 443
  frontend_node_pm2:
    hostname: frontend_node_pm2
    container_name: frontend_node_pm2
    build: .
    context: ./node_pm2
    expose:
      - 5000
